// source: case.def.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.covid19api.ExistingCaseDetail');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.covid19api.Location');

goog.forwardDeclare('proto.covid19api.CaseState');
goog.forwardDeclare('proto.covid19api.InfectionSource');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.ExistingCaseDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.covid19api.ExistingCaseDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.ExistingCaseDetail.displayName = 'proto.covid19api.ExistingCaseDetail';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.ExistingCaseDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.ExistingCaseDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.ExistingCaseDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.ExistingCaseDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    caseId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    patientId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    reportedTime: jspb.Message.getFieldWithDefault(msg, 3, 0),
    state: jspb.Message.getFieldWithDefault(msg, 11, 0),
    infectSrc: jspb.Message.getFieldWithDefault(msg, 12, 0),
    location: (f = msg.getLocation()) && proto.covid19api.Location.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.ExistingCaseDetail}
 */
proto.covid19api.ExistingCaseDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.ExistingCaseDetail;
  return proto.covid19api.ExistingCaseDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.ExistingCaseDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.ExistingCaseDetail}
 */
proto.covid19api.ExistingCaseDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaseId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReportedTime(value);
      break;
    case 11:
      var value = /** @type {!proto.covid19api.CaseState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 12:
      var value = /** @type {!proto.covid19api.InfectionSource} */ (reader.readEnum());
      msg.setInfectSrc(value);
      break;
    case 21:
      var value = new proto.covid19api.Location;
      reader.readMessage(value,proto.covid19api.Location.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.ExistingCaseDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.ExistingCaseDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.ExistingCaseDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.ExistingCaseDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCaseId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getReportedTime();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getInfectSrc();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      proto.covid19api.Location.serializeBinaryToWriter
    );
  }
};


/**
 * optional string case_id = 1;
 * @return {string}
 */
proto.covid19api.ExistingCaseDetail.prototype.getCaseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setCaseId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string patient_id = 2;
 * @return {string}
 */
proto.covid19api.ExistingCaseDetail.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 reported_time = 3;
 * @return {number}
 */
proto.covid19api.ExistingCaseDetail.prototype.getReportedTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setReportedTime = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional CaseState state = 11;
 * @return {!proto.covid19api.CaseState}
 */
proto.covid19api.ExistingCaseDetail.prototype.getState = function() {
  return /** @type {!proto.covid19api.CaseState} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {!proto.covid19api.CaseState} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional InfectionSource infect_src = 12;
 * @return {!proto.covid19api.InfectionSource}
 */
proto.covid19api.ExistingCaseDetail.prototype.getInfectSrc = function() {
  return /** @type {!proto.covid19api.InfectionSource} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.covid19api.InfectionSource} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setInfectSrc = function(value) {
  return jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * optional Location location = 21;
 * @return {?proto.covid19api.Location}
 */
proto.covid19api.ExistingCaseDetail.prototype.getLocation = function() {
  return /** @type{?proto.covid19api.Location} */ (
    jspb.Message.getWrapperField(this, proto.covid19api.Location, 21));
};


/**
 * @param {?proto.covid19api.Location|undefined} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
*/
proto.covid19api.ExistingCaseDetail.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.ExistingCaseDetail.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 21) != null;
};


