// source: case.def.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.covid19api.GetCasesRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.covid19api.Location');

goog.forwardDeclare('proto.covid19api.CaseState');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.GetCasesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.covid19api.GetCasesRequest.repeatedFields_, null);
};
goog.inherits(proto.covid19api.GetCasesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.GetCasesRequest.displayName = 'proto.covid19api.GetCasesRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.covid19api.GetCasesRequest.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.GetCasesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.GetCasesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.GetCasesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetCasesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    location: (f = msg.getLocation()) && proto.covid19api.Location.toObject(includeInstance, f),
    statesList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    startTime: jspb.Message.getFieldWithDefault(msg, 21, 0),
    endTime: jspb.Message.getFieldWithDefault(msg, 22, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.GetCasesRequest}
 */
proto.covid19api.GetCasesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.GetCasesRequest;
  return proto.covid19api.GetCasesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.GetCasesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.GetCasesRequest}
 */
proto.covid19api.GetCasesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.covid19api.Location;
      reader.readMessage(value,proto.covid19api.Location.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    case 11:
      var value = /** @type {!Array<!proto.covid19api.CaseState>} */ (reader.readPackedEnum());
      msg.setStatesList(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartTime(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.GetCasesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.GetCasesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.GetCasesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetCasesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.covid19api.Location.serializeBinaryToWriter
    );
  }
  f = message.getStatesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      11,
      f
    );
  }
  f = message.getStartTime();
  if (f !== 0) {
    writer.writeInt64(
      21,
      f
    );
  }
  f = message.getEndTime();
  if (f !== 0) {
    writer.writeInt64(
      22,
      f
    );
  }
};


/**
 * optional Location location = 1;
 * @return {?proto.covid19api.Location}
 */
proto.covid19api.GetCasesRequest.prototype.getLocation = function() {
  return /** @type{?proto.covid19api.Location} */ (
    jspb.Message.getWrapperField(this, proto.covid19api.Location, 1));
};


/**
 * @param {?proto.covid19api.Location|undefined} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
*/
proto.covid19api.GetCasesRequest.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.GetCasesRequest.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated CaseState states = 11;
 * @return {!Array<!proto.covid19api.CaseState>}
 */
proto.covid19api.GetCasesRequest.prototype.getStatesList = function() {
  return /** @type {!Array<!proto.covid19api.CaseState>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<!proto.covid19api.CaseState>} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.setStatesList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {!proto.covid19api.CaseState} value
 * @param {number=} opt_index
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.addStates = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.clearStatesList = function() {
  return this.setStatesList([]);
};


/**
 * optional int64 start_time = 21;
 * @return {number}
 */
proto.covid19api.GetCasesRequest.prototype.getStartTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.setStartTime = function(value) {
  return jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional int64 end_time = 22;
 * @return {number}
 */
proto.covid19api.GetCasesRequest.prototype.getEndTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.setEndTime = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


