// source: flight.def.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.covid19api.GetFlightsRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.GetFlightsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.covid19api.GetFlightsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.GetFlightsRequest.displayName = 'proto.covid19api.GetFlightsRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.GetFlightsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.GetFlightsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.GetFlightsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetFlightsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    flightNum: jspb.Message.getFieldWithDefault(msg, 1, ""),
    depDate: jspb.Message.getFieldWithDefault(msg, 4, 0),
    depAirport: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.GetFlightsRequest}
 */
proto.covid19api.GetFlightsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.GetFlightsRequest;
  return proto.covid19api.GetFlightsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.GetFlightsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.GetFlightsRequest}
 */
proto.covid19api.GetFlightsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFlightNum(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDepDate(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setDepAirport(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.GetFlightsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.GetFlightsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.GetFlightsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetFlightsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlightNum();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDepDate();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getDepAirport();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string flight_num = 1;
 * @return {string}
 */
proto.covid19api.GetFlightsRequest.prototype.getFlightNum = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.covid19api.GetFlightsRequest} returns this
 */
proto.covid19api.GetFlightsRequest.prototype.setFlightNum = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 dep_date = 4;
 * @return {number}
 */
proto.covid19api.GetFlightsRequest.prototype.getDepDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.covid19api.GetFlightsRequest} returns this
 */
proto.covid19api.GetFlightsRequest.prototype.setDepDate = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string dep_airport = 11;
 * @return {string}
 */
proto.covid19api.GetFlightsRequest.prototype.getDepAirport = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.covid19api.GetFlightsRequest} returns this
 */
proto.covid19api.GetFlightsRequest.prototype.setDepAirport = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


