// source: flight.def.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.covid19api.GetFlightsResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.covid19api.FlightDetail');
goog.require('proto.covid19api.Pagination');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.GetFlightsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.covid19api.GetFlightsResponse.repeatedFields_, null);
};
goog.inherits(proto.covid19api.GetFlightsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.GetFlightsResponse.displayName = 'proto.covid19api.GetFlightsResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.covid19api.GetFlightsResponse.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.GetFlightsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.GetFlightsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.GetFlightsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetFlightsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    pagination: (f = msg.getPagination()) && proto.covid19api.Pagination.toObject(includeInstance, f),
    flightsList: jspb.Message.toObjectList(msg.getFlightsList(),
    proto.covid19api.FlightDetail.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.GetFlightsResponse}
 */
proto.covid19api.GetFlightsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.GetFlightsResponse;
  return proto.covid19api.GetFlightsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.GetFlightsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.GetFlightsResponse}
 */
proto.covid19api.GetFlightsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.covid19api.Pagination;
      reader.readMessage(value,proto.covid19api.Pagination.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    case 11:
      var value = new proto.covid19api.FlightDetail;
      reader.readMessage(value,proto.covid19api.FlightDetail.deserializeBinaryFromReader);
      msg.addFlights(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.GetFlightsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.GetFlightsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.GetFlightsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetFlightsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.covid19api.Pagination.serializeBinaryToWriter
    );
  }
  f = message.getFlightsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.covid19api.FlightDetail.serializeBinaryToWriter
    );
  }
};


/**
 * optional Pagination pagination = 1;
 * @return {?proto.covid19api.Pagination}
 */
proto.covid19api.GetFlightsResponse.prototype.getPagination = function() {
  return /** @type{?proto.covid19api.Pagination} */ (
    jspb.Message.getWrapperField(this, proto.covid19api.Pagination, 1));
};


/**
 * @param {?proto.covid19api.Pagination|undefined} value
 * @return {!proto.covid19api.GetFlightsResponse} returns this
*/
proto.covid19api.GetFlightsResponse.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.GetFlightsResponse} returns this
 */
proto.covid19api.GetFlightsResponse.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.GetFlightsResponse.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated FlightDetail flights = 11;
 * @return {!Array<!proto.covid19api.FlightDetail>}
 */
proto.covid19api.GetFlightsResponse.prototype.getFlightsList = function() {
  return /** @type{!Array<!proto.covid19api.FlightDetail>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.covid19api.FlightDetail, 11));
};


/**
 * @param {!Array<!proto.covid19api.FlightDetail>} value
 * @return {!proto.covid19api.GetFlightsResponse} returns this
*/
proto.covid19api.GetFlightsResponse.prototype.setFlightsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.covid19api.FlightDetail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.covid19api.FlightDetail}
 */
proto.covid19api.GetFlightsResponse.prototype.addFlights = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.covid19api.FlightDetail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.covid19api.GetFlightsResponse} returns this
 */
proto.covid19api.GetFlightsResponse.prototype.clearFlightsList = function() {
  return this.setFlightsList([]);
};


