// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: flight.def.proto

package covid19api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FlightDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightNum    string   `protobuf:"bytes,1,opt,name=flight_num,json=flightNum,proto3" json:"flight_num,omitempty"`                   // Flight number
	IataCode     string   `protobuf:"bytes,2,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`                      // IATA code of airline
	IcaoCode     string   `protobuf:"bytes,3,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`                      // ICAO code of airline
	DepDate      int64    `protobuf:"varint,4,opt,name=dep_date,json=depDate,proto3" json:"dep_date,omitempty"`                        // Departure date
	ArrDate      int64    `protobuf:"varint,5,opt,name=arr_date,json=arrDate,proto3" json:"arr_date,omitempty"`                        // Arrival date
	DepAirport   string   `protobuf:"bytes,11,opt,name=dep_airport,json=depAirport,proto3" json:"dep_airport,omitempty"`               // Departure airport code
	ArrAirport   string   `protobuf:"bytes,12,opt,name=arr_airport,json=arrAirport,proto3" json:"arr_airport,omitempty"`               // Arrival airport code
	AffectedRows []uint32 `protobuf:"varint,21,rep,packed,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"` // Affected seating rows
}

func (x *FlightDetail) Reset() {
	*x = FlightDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_def_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightDetail) ProtoMessage() {}

func (x *FlightDetail) ProtoReflect() protoreflect.Message {
	mi := &file_flight_def_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightDetail.ProtoReflect.Descriptor instead.
func (*FlightDetail) Descriptor() ([]byte, []int) {
	return file_flight_def_proto_rawDescGZIP(), []int{0}
}

func (x *FlightDetail) GetFlightNum() string {
	if x != nil {
		return x.FlightNum
	}
	return ""
}

func (x *FlightDetail) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *FlightDetail) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

func (x *FlightDetail) GetDepDate() int64 {
	if x != nil {
		return x.DepDate
	}
	return 0
}

func (x *FlightDetail) GetArrDate() int64 {
	if x != nil {
		return x.ArrDate
	}
	return 0
}

func (x *FlightDetail) GetDepAirport() string {
	if x != nil {
		return x.DepAirport
	}
	return ""
}

func (x *FlightDetail) GetArrAirport() string {
	if x != nil {
		return x.ArrAirport
	}
	return ""
}

func (x *FlightDetail) GetAffectedRows() []uint32 {
	if x != nil {
		return x.AffectedRows
	}
	return nil
}

// GetFlightsRequest describes request payload for querying affected flights match specific criteria
type GetFlightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightNum  string `protobuf:"bytes,1,opt,name=flight_num,json=flightNum,proto3" json:"flight_num,omitempty"`
	DepDate    uint32 `protobuf:"varint,4,opt,name=dep_date,json=depDate,proto3" json:"dep_date,omitempty"`
	DepAirport string `protobuf:"bytes,11,opt,name=dep_airport,json=depAirport,proto3" json:"dep_airport,omitempty"`
}

func (x *GetFlightsRequest) Reset() {
	*x = GetFlightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_def_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsRequest) ProtoMessage() {}

func (x *GetFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_def_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsRequest.ProtoReflect.Descriptor instead.
func (*GetFlightsRequest) Descriptor() ([]byte, []int) {
	return file_flight_def_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlightsRequest) GetFlightNum() string {
	if x != nil {
		return x.FlightNum
	}
	return ""
}

func (x *GetFlightsRequest) GetDepDate() uint32 {
	if x != nil {
		return x.DepDate
	}
	return 0
}

func (x *GetFlightsRequest) GetDepAirport() string {
	if x != nil {
		return x.DepAirport
	}
	return ""
}

// GetFlightsResponse describes response payload for matched flights
type GetFlightsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Flights    []*FlightDetail `protobuf:"bytes,11,rep,name=flights,proto3" json:"flights,omitempty"`
}

func (x *GetFlightsResponse) Reset() {
	*x = GetFlightsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_def_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightsResponse) ProtoMessage() {}

func (x *GetFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_def_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightsResponse.ProtoReflect.Descriptor instead.
func (*GetFlightsResponse) Descriptor() ([]byte, []int) {
	return file_flight_def_proto_rawDescGZIP(), []int{2}
}

func (x *GetFlightsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetFlightsResponse) GetFlights() []*FlightDetail {
	if x != nil {
		return x.Flights
	}
	return nil
}

// AddFlightsRequest describes request payload for adding affected flights
type AddFlightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*FlightDetail `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
}

func (x *AddFlightsRequest) Reset() {
	*x = AddFlightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_def_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFlightsRequest) ProtoMessage() {}

func (x *AddFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_def_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFlightsRequest.ProtoReflect.Descriptor instead.
func (*AddFlightsRequest) Descriptor() ([]byte, []int) {
	return file_flight_def_proto_rawDescGZIP(), []int{3}
}

func (x *AddFlightsRequest) GetFlights() []*FlightDetail {
	if x != nil {
		return x.Flights
	}
	return nil
}

// DelFlightsRequest describes request payload for deleting affected flights
type DelFlightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*DelFlightsRequest_FlightIdentifier `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
}

func (x *DelFlightsRequest) Reset() {
	*x = DelFlightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_def_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFlightsRequest) ProtoMessage() {}

func (x *DelFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_def_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFlightsRequest.ProtoReflect.Descriptor instead.
func (*DelFlightsRequest) Descriptor() ([]byte, []int) {
	return file_flight_def_proto_rawDescGZIP(), []int{4}
}

func (x *DelFlightsRequest) GetFlights() []*DelFlightsRequest_FlightIdentifier {
	if x != nil {
		return x.Flights
	}
	return nil
}

type DelFlightsRequest_FlightIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightNum string `protobuf:"bytes,1,opt,name=flight_num,json=flightNum,proto3" json:"flight_num,omitempty"` // Flight number
	DepDate   uint32 `protobuf:"varint,2,opt,name=dep_date,json=depDate,proto3" json:"dep_date,omitempty"`      // Departure date
}

func (x *DelFlightsRequest_FlightIdentifier) Reset() {
	*x = DelFlightsRequest_FlightIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_def_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFlightsRequest_FlightIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFlightsRequest_FlightIdentifier) ProtoMessage() {}

func (x *DelFlightsRequest_FlightIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_flight_def_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFlightsRequest_FlightIdentifier.ProtoReflect.Descriptor instead.
func (*DelFlightsRequest_FlightIdentifier) Descriptor() ([]byte, []int) {
	return file_flight_def_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DelFlightsRequest_FlightIdentifier) GetFlightNum() string {
	if x != nil {
		return x.FlightNum
	}
	return ""
}

func (x *DelFlightsRequest_FlightIdentifier) GetDepDate() uint32 {
	if x != nil {
		return x.DepDate
	}
	return 0
}

var File_flight_def_proto protoreflect.FileDescriptor

var file_flight_def_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x31, 0x39, 0x61, 0x70, 0x69, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x02, 0x0a,
	0x0c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x61,
	0x6f, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x63,
	0x61, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x70, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x72, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x72, 0x72, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x65, 0x70, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x61, 0x72, 0x72, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x72, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18,
	0x15, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52,
	0x6f, 0x77, 0x73, 0x22, 0x6e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x65, 0x70, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x70, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x41, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x31, 0x39, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x31, 0x39, 0x61, 0x70, 0x69,
	0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x6f, 0x76, 0x69, 0x64, 0x31, 0x39, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22,
	0xab, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x31, 0x39,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x1a,
	0x4c, 0x0a, 0x10, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e,
	0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x65, 0x70, 0x44, 0x61, 0x74, 0x65, 0x42, 0x37, 0x0a,
	0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x31, 0x39, 0x2e, 0x61, 0x70, 0x69,
	0x42, 0x14, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0c, 0x2e, 0x3b, 0x63, 0x6f, 0x76, 0x69,
	0x64, 0x31, 0x39, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flight_def_proto_rawDescOnce sync.Once
	file_flight_def_proto_rawDescData = file_flight_def_proto_rawDesc
)

func file_flight_def_proto_rawDescGZIP() []byte {
	file_flight_def_proto_rawDescOnce.Do(func() {
		file_flight_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_flight_def_proto_rawDescData)
	})
	return file_flight_def_proto_rawDescData
}

var file_flight_def_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_flight_def_proto_goTypes = []interface{}{
	(*FlightDetail)(nil),                       // 0: covid19api.FlightDetail
	(*GetFlightsRequest)(nil),                  // 1: covid19api.GetFlightsRequest
	(*GetFlightsResponse)(nil),                 // 2: covid19api.GetFlightsResponse
	(*AddFlightsRequest)(nil),                  // 3: covid19api.AddFlightsRequest
	(*DelFlightsRequest)(nil),                  // 4: covid19api.DelFlightsRequest
	(*DelFlightsRequest_FlightIdentifier)(nil), // 5: covid19api.DelFlightsRequest.FlightIdentifier
	(*Pagination)(nil),                         // 6: covid19api.Pagination
}
var file_flight_def_proto_depIdxs = []int32{
	6, // 0: covid19api.GetFlightsResponse.pagination:type_name -> covid19api.Pagination
	0, // 1: covid19api.GetFlightsResponse.flights:type_name -> covid19api.FlightDetail
	0, // 2: covid19api.AddFlightsRequest.flights:type_name -> covid19api.FlightDetail
	5, // 3: covid19api.DelFlightsRequest.flights:type_name -> covid19api.DelFlightsRequest.FlightIdentifier
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_flight_def_proto_init() }
func file_flight_def_proto_init() {
	if File_flight_def_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_flight_def_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_def_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_def_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlightsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_def_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFlightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_def_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFlightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_def_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFlightsRequest_FlightIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flight_def_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flight_def_proto_goTypes,
		DependencyIndexes: file_flight_def_proto_depIdxs,
		MessageInfos:      file_flight_def_proto_msgTypes,
	}.Build()
	File_flight_def_proto = out.File
	file_flight_def_proto_rawDesc = nil
	file_flight_def_proto_goTypes = nil
	file_flight_def_proto_depIdxs = nil
}
