// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flight.def.proto

package covid19api

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FlightDetail) Validate() error {
	return nil
}
func (this *GetFlightsRequest) Validate() error {
	return nil
}
func (this *GetFlightsResponse) Validate() error {
	if this.Pagination != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Pagination); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Pagination", err)
		}
	}
	for _, item := range this.Flights {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Flights", err)
			}
		}
	}
	return nil
}
func (this *AddFlightsRequest) Validate() error {
	for _, item := range this.Flights {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Flights", err)
			}
		}
	}
	return nil
}
func (this *DelFlightsRequest) Validate() error {
	for _, item := range this.Flights {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Flights", err)
			}
		}
	}
	return nil
}
func (this *DelFlightsRequest_FlightIdentifier) Validate() error {
	return nil
}
