// source: flight.def.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.covid19api.DelFlightsRequest');
goog.provide('proto.covid19api.DelFlightsRequest.FlightIdentifier');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.DelFlightsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.covid19api.DelFlightsRequest.repeatedFields_, null);
};
goog.inherits(proto.covid19api.DelFlightsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.DelFlightsRequest.displayName = 'proto.covid19api.DelFlightsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.covid19api.DelFlightsRequest.FlightIdentifier, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.DelFlightsRequest.FlightIdentifier.displayName = 'proto.covid19api.DelFlightsRequest.FlightIdentifier';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.covid19api.DelFlightsRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.DelFlightsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.DelFlightsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.DelFlightsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.DelFlightsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    flightsList: jspb.Message.toObjectList(msg.getFlightsList(),
    proto.covid19api.DelFlightsRequest.FlightIdentifier.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.DelFlightsRequest}
 */
proto.covid19api.DelFlightsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.DelFlightsRequest;
  return proto.covid19api.DelFlightsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.DelFlightsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.DelFlightsRequest}
 */
proto.covid19api.DelFlightsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.covid19api.DelFlightsRequest.FlightIdentifier;
      reader.readMessage(value,proto.covid19api.DelFlightsRequest.FlightIdentifier.deserializeBinaryFromReader);
      msg.addFlights(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.DelFlightsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.DelFlightsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.DelFlightsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.DelFlightsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlightsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.covid19api.DelFlightsRequest.FlightIdentifier.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.DelFlightsRequest.FlightIdentifier.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.DelFlightsRequest.FlightIdentifier} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.toObject = function(includeInstance, msg) {
  var f, obj = {
    flightNum: jspb.Message.getFieldWithDefault(msg, 1, ""),
    depDate: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.DelFlightsRequest.FlightIdentifier}
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.DelFlightsRequest.FlightIdentifier;
  return proto.covid19api.DelFlightsRequest.FlightIdentifier.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.DelFlightsRequest.FlightIdentifier} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.DelFlightsRequest.FlightIdentifier}
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFlightNum(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDepDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.DelFlightsRequest.FlightIdentifier.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.DelFlightsRequest.FlightIdentifier} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlightNum();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDepDate();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional string flight_num = 1;
 * @return {string}
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.prototype.getFlightNum = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.covid19api.DelFlightsRequest.FlightIdentifier} returns this
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.prototype.setFlightNum = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 dep_date = 2;
 * @return {number}
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.prototype.getDepDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.covid19api.DelFlightsRequest.FlightIdentifier} returns this
 */
proto.covid19api.DelFlightsRequest.FlightIdentifier.prototype.setDepDate = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated FlightIdentifier flights = 1;
 * @return {!Array<!proto.covid19api.DelFlightsRequest.FlightIdentifier>}
 */
proto.covid19api.DelFlightsRequest.prototype.getFlightsList = function() {
  return /** @type{!Array<!proto.covid19api.DelFlightsRequest.FlightIdentifier>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.covid19api.DelFlightsRequest.FlightIdentifier, 1));
};


/**
 * @param {!Array<!proto.covid19api.DelFlightsRequest.FlightIdentifier>} value
 * @return {!proto.covid19api.DelFlightsRequest} returns this
*/
proto.covid19api.DelFlightsRequest.prototype.setFlightsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.covid19api.DelFlightsRequest.FlightIdentifier=} opt_value
 * @param {number=} opt_index
 * @return {!proto.covid19api.DelFlightsRequest.FlightIdentifier}
 */
proto.covid19api.DelFlightsRequest.prototype.addFlights = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.covid19api.DelFlightsRequest.FlightIdentifier, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.covid19api.DelFlightsRequest} returns this
 */
proto.covid19api.DelFlightsRequest.prototype.clearFlightsList = function() {
  return this.setFlightsList([]);
};


