// source: case.def.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.covid19api.ExistingCaseDetail');
goog.provide('proto.covid19api.ExistingCaseDetail.LocationCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.covid19api.GPSLocation');
goog.require('proto.covid19api.NamedLocation');
goog.require('proto.google.protobuf.Timestamp');

goog.forwardDeclare('proto.covid19api.CaseState');
goog.forwardDeclare('proto.covid19api.InfectionSource');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.ExistingCaseDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.covid19api.ExistingCaseDetail.oneofGroups_);
};
goog.inherits(proto.covid19api.ExistingCaseDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.ExistingCaseDetail.displayName = 'proto.covid19api.ExistingCaseDetail';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.covid19api.ExistingCaseDetail.oneofGroups_ = [[21,22]];

/**
 * @enum {number}
 */
proto.covid19api.ExistingCaseDetail.LocationCase = {
  LOCATION_NOT_SET: 0,
  NAMED_LOCATION: 21,
  GPS_LOCATION: 22
};

/**
 * @return {proto.covid19api.ExistingCaseDetail.LocationCase}
 */
proto.covid19api.ExistingCaseDetail.prototype.getLocationCase = function() {
  return /** @type {proto.covid19api.ExistingCaseDetail.LocationCase} */(jspb.Message.computeOneofCase(this, proto.covid19api.ExistingCaseDetail.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.ExistingCaseDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.ExistingCaseDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.ExistingCaseDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.ExistingCaseDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    caseUuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    patientId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    reportedTime: (f = msg.getReportedTime()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    state: jspb.Message.getFieldWithDefault(msg, 11, 0),
    infectSrc: jspb.Message.getFieldWithDefault(msg, 12, 0),
    namedLocation: (f = msg.getNamedLocation()) && proto.covid19api.NamedLocation.toObject(includeInstance, f),
    gpsLocation: (f = msg.getGpsLocation()) && proto.covid19api.GPSLocation.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.ExistingCaseDetail}
 */
proto.covid19api.ExistingCaseDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.ExistingCaseDetail;
  return proto.covid19api.ExistingCaseDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.ExistingCaseDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.ExistingCaseDetail}
 */
proto.covid19api.ExistingCaseDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaseUuid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 3:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setReportedTime(value);
      break;
    case 11:
      var value = /** @type {!proto.covid19api.CaseState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 12:
      var value = /** @type {!proto.covid19api.InfectionSource} */ (reader.readEnum());
      msg.setInfectSrc(value);
      break;
    case 21:
      var value = new proto.covid19api.NamedLocation;
      reader.readMessage(value,proto.covid19api.NamedLocation.deserializeBinaryFromReader);
      msg.setNamedLocation(value);
      break;
    case 22:
      var value = new proto.covid19api.GPSLocation;
      reader.readMessage(value,proto.covid19api.GPSLocation.deserializeBinaryFromReader);
      msg.setGpsLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.ExistingCaseDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.ExistingCaseDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.ExistingCaseDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.ExistingCaseDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCaseUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getReportedTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getInfectSrc();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getNamedLocation();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      proto.covid19api.NamedLocation.serializeBinaryToWriter
    );
  }
  f = message.getGpsLocation();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      proto.covid19api.GPSLocation.serializeBinaryToWriter
    );
  }
};


/**
 * optional string case_uuid = 1;
 * @return {string}
 */
proto.covid19api.ExistingCaseDetail.prototype.getCaseUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setCaseUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string patient_id = 2;
 * @return {string}
 */
proto.covid19api.ExistingCaseDetail.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp reported_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.covid19api.ExistingCaseDetail.prototype.getReportedTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
*/
proto.covid19api.ExistingCaseDetail.prototype.setReportedTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.clearReportedTime = function() {
  return this.setReportedTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.ExistingCaseDetail.prototype.hasReportedTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CaseState state = 11;
 * @return {!proto.covid19api.CaseState}
 */
proto.covid19api.ExistingCaseDetail.prototype.getState = function() {
  return /** @type {!proto.covid19api.CaseState} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {!proto.covid19api.CaseState} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional InfectionSource infect_src = 12;
 * @return {!proto.covid19api.InfectionSource}
 */
proto.covid19api.ExistingCaseDetail.prototype.getInfectSrc = function() {
  return /** @type {!proto.covid19api.InfectionSource} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.covid19api.InfectionSource} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.setInfectSrc = function(value) {
  return jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * optional NamedLocation named_location = 21;
 * @return {?proto.covid19api.NamedLocation}
 */
proto.covid19api.ExistingCaseDetail.prototype.getNamedLocation = function() {
  return /** @type{?proto.covid19api.NamedLocation} */ (
    jspb.Message.getWrapperField(this, proto.covid19api.NamedLocation, 21));
};


/**
 * @param {?proto.covid19api.NamedLocation|undefined} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
*/
proto.covid19api.ExistingCaseDetail.prototype.setNamedLocation = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.covid19api.ExistingCaseDetail.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.clearNamedLocation = function() {
  return this.setNamedLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.ExistingCaseDetail.prototype.hasNamedLocation = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional GPSLocation gps_location = 22;
 * @return {?proto.covid19api.GPSLocation}
 */
proto.covid19api.ExistingCaseDetail.prototype.getGpsLocation = function() {
  return /** @type{?proto.covid19api.GPSLocation} */ (
    jspb.Message.getWrapperField(this, proto.covid19api.GPSLocation, 22));
};


/**
 * @param {?proto.covid19api.GPSLocation|undefined} value
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
*/
proto.covid19api.ExistingCaseDetail.prototype.setGpsLocation = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.covid19api.ExistingCaseDetail.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.ExistingCaseDetail} returns this
 */
proto.covid19api.ExistingCaseDetail.prototype.clearGpsLocation = function() {
  return this.setGpsLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.ExistingCaseDetail.prototype.hasGpsLocation = function() {
  return jspb.Message.getField(this, 22) != null;
};


