// source: case.def.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.covid19api.GetCasesRequest');
goog.provide('proto.covid19api.GetCasesRequest.LocationCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.covid19api.GPSLocation');
goog.require('proto.covid19api.NamedLocation');
goog.require('proto.google.protobuf.Timestamp');

goog.forwardDeclare('proto.covid19api.CaseState');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.covid19api.GetCasesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.covid19api.GetCasesRequest.repeatedFields_, proto.covid19api.GetCasesRequest.oneofGroups_);
};
goog.inherits(proto.covid19api.GetCasesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.covid19api.GetCasesRequest.displayName = 'proto.covid19api.GetCasesRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.covid19api.GetCasesRequest.repeatedFields_ = [11];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.covid19api.GetCasesRequest.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.covid19api.GetCasesRequest.LocationCase = {
  LOCATION_NOT_SET: 0,
  NAMED_LOCATION: 1,
  GPS_LOCATION: 2
};

/**
 * @return {proto.covid19api.GetCasesRequest.LocationCase}
 */
proto.covid19api.GetCasesRequest.prototype.getLocationCase = function() {
  return /** @type {proto.covid19api.GetCasesRequest.LocationCase} */(jspb.Message.computeOneofCase(this, proto.covid19api.GetCasesRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.covid19api.GetCasesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.covid19api.GetCasesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.covid19api.GetCasesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetCasesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    namedLocation: (f = msg.getNamedLocation()) && proto.covid19api.NamedLocation.toObject(includeInstance, f),
    gpsLocation: (f = msg.getGpsLocation()) && proto.covid19api.GPSLocation.toObject(includeInstance, f),
    statesList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    startTime: (f = msg.getStartTime()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    endTime: (f = msg.getEndTime()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.covid19api.GetCasesRequest}
 */
proto.covid19api.GetCasesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.covid19api.GetCasesRequest;
  return proto.covid19api.GetCasesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.covid19api.GetCasesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.covid19api.GetCasesRequest}
 */
proto.covid19api.GetCasesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.covid19api.NamedLocation;
      reader.readMessage(value,proto.covid19api.NamedLocation.deserializeBinaryFromReader);
      msg.setNamedLocation(value);
      break;
    case 2:
      var value = new proto.covid19api.GPSLocation;
      reader.readMessage(value,proto.covid19api.GPSLocation.deserializeBinaryFromReader);
      msg.setGpsLocation(value);
      break;
    case 11:
      var value = /** @type {!Array<!proto.covid19api.CaseState>} */ (reader.readPackedEnum());
      msg.setStatesList(value);
      break;
    case 21:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 22:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.covid19api.GetCasesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.covid19api.GetCasesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.covid19api.GetCasesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.covid19api.GetCasesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNamedLocation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.covid19api.NamedLocation.serializeBinaryToWriter
    );
  }
  f = message.getGpsLocation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.covid19api.GPSLocation.serializeBinaryToWriter
    );
  }
  f = message.getStatesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      11,
      f
    );
  }
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional NamedLocation named_location = 1;
 * @return {?proto.covid19api.NamedLocation}
 */
proto.covid19api.GetCasesRequest.prototype.getNamedLocation = function() {
  return /** @type{?proto.covid19api.NamedLocation} */ (
    jspb.Message.getWrapperField(this, proto.covid19api.NamedLocation, 1));
};


/**
 * @param {?proto.covid19api.NamedLocation|undefined} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
*/
proto.covid19api.GetCasesRequest.prototype.setNamedLocation = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.covid19api.GetCasesRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.clearNamedLocation = function() {
  return this.setNamedLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.GetCasesRequest.prototype.hasNamedLocation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GPSLocation gps_location = 2;
 * @return {?proto.covid19api.GPSLocation}
 */
proto.covid19api.GetCasesRequest.prototype.getGpsLocation = function() {
  return /** @type{?proto.covid19api.GPSLocation} */ (
    jspb.Message.getWrapperField(this, proto.covid19api.GPSLocation, 2));
};


/**
 * @param {?proto.covid19api.GPSLocation|undefined} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
*/
proto.covid19api.GetCasesRequest.prototype.setGpsLocation = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.covid19api.GetCasesRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.clearGpsLocation = function() {
  return this.setGpsLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.GetCasesRequest.prototype.hasGpsLocation = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated CaseState states = 11;
 * @return {!Array<!proto.covid19api.CaseState>}
 */
proto.covid19api.GetCasesRequest.prototype.getStatesList = function() {
  return /** @type {!Array<!proto.covid19api.CaseState>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<!proto.covid19api.CaseState>} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.setStatesList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {!proto.covid19api.CaseState} value
 * @param {number=} opt_index
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.addStates = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.clearStatesList = function() {
  return this.setStatesList([]);
};


/**
 * optional google.protobuf.Timestamp start_time = 21;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.covid19api.GetCasesRequest.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 21));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
*/
proto.covid19api.GetCasesRequest.prototype.setStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.clearStartTime = function() {
  return this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.GetCasesRequest.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional google.protobuf.Timestamp end_time = 22;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.covid19api.GetCasesRequest.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 22));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.covid19api.GetCasesRequest} returns this
*/
proto.covid19api.GetCasesRequest.prototype.setEndTime = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.covid19api.GetCasesRequest} returns this
 */
proto.covid19api.GetCasesRequest.prototype.clearEndTime = function() {
  return this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.covid19api.GetCasesRequest.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 22) != null;
};


