// Code generated by protoc-gen-go. DO NOT EDIT.
// source: case.def.proto

package org_covid19_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CaseState describes state of the case
type CaseState int32

const (
	CaseState_UNKNOWN     CaseState = 0
	CaseState_UNDISCLOSED CaseState = 1
	CaseState_CONFIRMED   CaseState = 11
	CaseState_RECOVERED   CaseState = 12
	CaseState_DEATH       CaseState = 13
)

var CaseState_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "UNDISCLOSED",
	11: "CONFIRMED",
	12: "RECOVERED",
	13: "DEATH",
}

var CaseState_value = map[string]int32{
	"UNKNOWN":     0,
	"UNDISCLOSED": 1,
	"CONFIRMED":   11,
	"RECOVERED":   12,
	"DEATH":       13,
}

func (x CaseState) String() string {
	return proto.EnumName(CaseState_name, int32(x))
}

func (CaseState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{0}
}

// InfectionSource describes source of the infection
type InfectionSource int32

const (
	InfectionSource_DOMESTIC      InfectionSource = 0
	InfectionSource_INTL_IMPORTED InfectionSource = 1
	InfectionSource_SHIP_IMPORTED InfectionSource = 2
)

var InfectionSource_name = map[int32]string{
	0: "DOMESTIC",
	1: "INTL_IMPORTED",
	2: "SHIP_IMPORTED",
}

var InfectionSource_value = map[string]int32{
	"DOMESTIC":      0,
	"INTL_IMPORTED": 1,
	"SHIP_IMPORTED": 2,
}

func (x InfectionSource) String() string {
	return proto.EnumName(InfectionSource_name, int32(x))
}

func (InfectionSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{1}
}

// ExistingCaseDetail describes an existing (exists in DB) case
type ExistingCaseDetail struct {
	CaseUuid     string               `protobuf:"bytes,1,opt,name=case_uuid,json=caseUuid,proto3" json:"case_uuid,omitempty"`
	PatientId    string               `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ReportedTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=reported_time,json=reportedTime,proto3" json:"reported_time,omitempty"`
	State        CaseState            `protobuf:"varint,11,opt,name=state,proto3,enum=org.covid19.api.CaseState" json:"state,omitempty"`
	InfectSrc    InfectionSource      `protobuf:"varint,12,opt,name=infect_src,json=infectSrc,proto3,enum=org.covid19.api.InfectionSource" json:"infect_src,omitempty"`
	// Types that are valid to be assigned to Location:
	//	*ExistingCaseDetail_NamedLocation
	//	*ExistingCaseDetail_GpsLocation
	Location             isExistingCaseDetail_Location `protobuf_oneof:"location"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ExistingCaseDetail) Reset()         { *m = ExistingCaseDetail{} }
func (m *ExistingCaseDetail) String() string { return proto.CompactTextString(m) }
func (*ExistingCaseDetail) ProtoMessage()    {}
func (*ExistingCaseDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{0}
}

func (m *ExistingCaseDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistingCaseDetail.Unmarshal(m, b)
}
func (m *ExistingCaseDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistingCaseDetail.Marshal(b, m, deterministic)
}
func (m *ExistingCaseDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistingCaseDetail.Merge(m, src)
}
func (m *ExistingCaseDetail) XXX_Size() int {
	return xxx_messageInfo_ExistingCaseDetail.Size(m)
}
func (m *ExistingCaseDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistingCaseDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ExistingCaseDetail proto.InternalMessageInfo

func (m *ExistingCaseDetail) GetCaseUuid() string {
	if m != nil {
		return m.CaseUuid
	}
	return ""
}

func (m *ExistingCaseDetail) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *ExistingCaseDetail) GetReportedTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReportedTime
	}
	return nil
}

func (m *ExistingCaseDetail) GetState() CaseState {
	if m != nil {
		return m.State
	}
	return CaseState_UNKNOWN
}

func (m *ExistingCaseDetail) GetInfectSrc() InfectionSource {
	if m != nil {
		return m.InfectSrc
	}
	return InfectionSource_DOMESTIC
}

type isExistingCaseDetail_Location interface {
	isExistingCaseDetail_Location()
}

type ExistingCaseDetail_NamedLocation struct {
	NamedLocation *NamedLocation `protobuf:"bytes,21,opt,name=named_location,json=namedLocation,proto3,oneof"`
}

type ExistingCaseDetail_GpsLocation struct {
	GpsLocation *GPSLocation `protobuf:"bytes,22,opt,name=gps_location,json=gpsLocation,proto3,oneof"`
}

func (*ExistingCaseDetail_NamedLocation) isExistingCaseDetail_Location() {}

func (*ExistingCaseDetail_GpsLocation) isExistingCaseDetail_Location() {}

func (m *ExistingCaseDetail) GetLocation() isExistingCaseDetail_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *ExistingCaseDetail) GetNamedLocation() *NamedLocation {
	if x, ok := m.GetLocation().(*ExistingCaseDetail_NamedLocation); ok {
		return x.NamedLocation
	}
	return nil
}

func (m *ExistingCaseDetail) GetGpsLocation() *GPSLocation {
	if x, ok := m.GetLocation().(*ExistingCaseDetail_GpsLocation); ok {
		return x.GpsLocation
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExistingCaseDetail) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExistingCaseDetail_NamedLocation)(nil),
		(*ExistingCaseDetail_GpsLocation)(nil),
	}
}

// NewCaseDetail describes a new (not exists in DB) case
type NewCaseDetail struct {
	PatientId    string               `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ReportedTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=reported_time,json=reportedTime,proto3" json:"reported_time,omitempty"`
	State        CaseState            `protobuf:"varint,11,opt,name=state,proto3,enum=org.covid19.api.CaseState" json:"state,omitempty"`
	InfectSrc    InfectionSource      `protobuf:"varint,12,opt,name=infect_src,json=infectSrc,proto3,enum=org.covid19.api.InfectionSource" json:"infect_src,omitempty"`
	// Types that are valid to be assigned to Location:
	//	*NewCaseDetail_NamedLocation
	//	*NewCaseDetail_GpsLocation
	Location             isNewCaseDetail_Location `protobuf_oneof:"location"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *NewCaseDetail) Reset()         { *m = NewCaseDetail{} }
func (m *NewCaseDetail) String() string { return proto.CompactTextString(m) }
func (*NewCaseDetail) ProtoMessage()    {}
func (*NewCaseDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{1}
}

func (m *NewCaseDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCaseDetail.Unmarshal(m, b)
}
func (m *NewCaseDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCaseDetail.Marshal(b, m, deterministic)
}
func (m *NewCaseDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCaseDetail.Merge(m, src)
}
func (m *NewCaseDetail) XXX_Size() int {
	return xxx_messageInfo_NewCaseDetail.Size(m)
}
func (m *NewCaseDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCaseDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NewCaseDetail proto.InternalMessageInfo

func (m *NewCaseDetail) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *NewCaseDetail) GetReportedTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReportedTime
	}
	return nil
}

func (m *NewCaseDetail) GetState() CaseState {
	if m != nil {
		return m.State
	}
	return CaseState_UNKNOWN
}

func (m *NewCaseDetail) GetInfectSrc() InfectionSource {
	if m != nil {
		return m.InfectSrc
	}
	return InfectionSource_DOMESTIC
}

type isNewCaseDetail_Location interface {
	isNewCaseDetail_Location()
}

type NewCaseDetail_NamedLocation struct {
	NamedLocation *NamedLocation `protobuf:"bytes,21,opt,name=named_location,json=namedLocation,proto3,oneof"`
}

type NewCaseDetail_GpsLocation struct {
	GpsLocation *GPSLocation `protobuf:"bytes,22,opt,name=gps_location,json=gpsLocation,proto3,oneof"`
}

func (*NewCaseDetail_NamedLocation) isNewCaseDetail_Location() {}

func (*NewCaseDetail_GpsLocation) isNewCaseDetail_Location() {}

func (m *NewCaseDetail) GetLocation() isNewCaseDetail_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *NewCaseDetail) GetNamedLocation() *NamedLocation {
	if x, ok := m.GetLocation().(*NewCaseDetail_NamedLocation); ok {
		return x.NamedLocation
	}
	return nil
}

func (m *NewCaseDetail) GetGpsLocation() *GPSLocation {
	if x, ok := m.GetLocation().(*NewCaseDetail_GpsLocation); ok {
		return x.GpsLocation
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NewCaseDetail) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NewCaseDetail_NamedLocation)(nil),
		(*NewCaseDetail_GpsLocation)(nil),
	}
}

// GetCasesRequest describes request payload for querying cases match specific criteria
type GetCasesRequest struct {
	// Types that are valid to be assigned to Location:
	//	*GetCasesRequest_NamedLocation
	//	*GetCasesRequest_GpsLocation
	Location             isGetCasesRequest_Location `protobuf_oneof:"location"`
	States               []CaseState                `protobuf:"varint,11,rep,packed,name=states,proto3,enum=org.covid19.api.CaseState" json:"states,omitempty"`
	StartTime            *timestamp.Timestamp       `protobuf:"bytes,21,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp       `protobuf:"bytes,22,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetCasesRequest) Reset()         { *m = GetCasesRequest{} }
func (m *GetCasesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCasesRequest) ProtoMessage()    {}
func (*GetCasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{2}
}

func (m *GetCasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCasesRequest.Unmarshal(m, b)
}
func (m *GetCasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCasesRequest.Marshal(b, m, deterministic)
}
func (m *GetCasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCasesRequest.Merge(m, src)
}
func (m *GetCasesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCasesRequest.Size(m)
}
func (m *GetCasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCasesRequest proto.InternalMessageInfo

type isGetCasesRequest_Location interface {
	isGetCasesRequest_Location()
}

type GetCasesRequest_NamedLocation struct {
	NamedLocation *NamedLocation `protobuf:"bytes,1,opt,name=named_location,json=namedLocation,proto3,oneof"`
}

type GetCasesRequest_GpsLocation struct {
	GpsLocation *GPSLocation `protobuf:"bytes,2,opt,name=gps_location,json=gpsLocation,proto3,oneof"`
}

func (*GetCasesRequest_NamedLocation) isGetCasesRequest_Location() {}

func (*GetCasesRequest_GpsLocation) isGetCasesRequest_Location() {}

func (m *GetCasesRequest) GetLocation() isGetCasesRequest_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetCasesRequest) GetNamedLocation() *NamedLocation {
	if x, ok := m.GetLocation().(*GetCasesRequest_NamedLocation); ok {
		return x.NamedLocation
	}
	return nil
}

func (m *GetCasesRequest) GetGpsLocation() *GPSLocation {
	if x, ok := m.GetLocation().(*GetCasesRequest_GpsLocation); ok {
		return x.GpsLocation
	}
	return nil
}

func (m *GetCasesRequest) GetStates() []CaseState {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *GetCasesRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GetCasesRequest) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetCasesRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetCasesRequest_NamedLocation)(nil),
		(*GetCasesRequest_GpsLocation)(nil),
	}
}

// GetCasesResponse describes response payload for matched cases
type GetCasesResponse struct {
	Pagination           *Pagination           `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Cases                []*ExistingCaseDetail `protobuf:"bytes,11,rep,name=cases,proto3" json:"cases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetCasesResponse) Reset()         { *m = GetCasesResponse{} }
func (m *GetCasesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCasesResponse) ProtoMessage()    {}
func (*GetCasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{3}
}

func (m *GetCasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCasesResponse.Unmarshal(m, b)
}
func (m *GetCasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCasesResponse.Marshal(b, m, deterministic)
}
func (m *GetCasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCasesResponse.Merge(m, src)
}
func (m *GetCasesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCasesResponse.Size(m)
}
func (m *GetCasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCasesResponse proto.InternalMessageInfo

func (m *GetCasesResponse) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetCasesResponse) GetCases() []*ExistingCaseDetail {
	if m != nil {
		return m.Cases
	}
	return nil
}

// AddCasesRequest describes request payload for adding cases
type AddCasesRequest struct {
	Cases                []*NewCaseDetail `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddCasesRequest) Reset()         { *m = AddCasesRequest{} }
func (m *AddCasesRequest) String() string { return proto.CompactTextString(m) }
func (*AddCasesRequest) ProtoMessage()    {}
func (*AddCasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{4}
}

func (m *AddCasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCasesRequest.Unmarshal(m, b)
}
func (m *AddCasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCasesRequest.Marshal(b, m, deterministic)
}
func (m *AddCasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCasesRequest.Merge(m, src)
}
func (m *AddCasesRequest) XXX_Size() int {
	return xxx_messageInfo_AddCasesRequest.Size(m)
}
func (m *AddCasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCasesRequest proto.InternalMessageInfo

func (m *AddCasesRequest) GetCases() []*NewCaseDetail {
	if m != nil {
		return m.Cases
	}
	return nil
}

// PutCasesRequest describes request payload for updating existing cases
type PutCasesRequest struct {
	Cases                []*ExistingCaseDetail `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PutCasesRequest) Reset()         { *m = PutCasesRequest{} }
func (m *PutCasesRequest) String() string { return proto.CompactTextString(m) }
func (*PutCasesRequest) ProtoMessage()    {}
func (*PutCasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{5}
}

func (m *PutCasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutCasesRequest.Unmarshal(m, b)
}
func (m *PutCasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutCasesRequest.Marshal(b, m, deterministic)
}
func (m *PutCasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutCasesRequest.Merge(m, src)
}
func (m *PutCasesRequest) XXX_Size() int {
	return xxx_messageInfo_PutCasesRequest.Size(m)
}
func (m *PutCasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutCasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutCasesRequest proto.InternalMessageInfo

func (m *PutCasesRequest) GetCases() []*ExistingCaseDetail {
	if m != nil {
		return m.Cases
	}
	return nil
}

// DelCasesRequest describes request payload for deleting existing cases
type DelCasesRequest struct {
	CaseUuids            []string `protobuf:"bytes,1,rep,name=case_uuids,json=caseUuids,proto3" json:"case_uuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCasesRequest) Reset()         { *m = DelCasesRequest{} }
func (m *DelCasesRequest) String() string { return proto.CompactTextString(m) }
func (*DelCasesRequest) ProtoMessage()    {}
func (*DelCasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c687d06fd30aa5ff, []int{6}
}

func (m *DelCasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCasesRequest.Unmarshal(m, b)
}
func (m *DelCasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCasesRequest.Marshal(b, m, deterministic)
}
func (m *DelCasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCasesRequest.Merge(m, src)
}
func (m *DelCasesRequest) XXX_Size() int {
	return xxx_messageInfo_DelCasesRequest.Size(m)
}
func (m *DelCasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelCasesRequest proto.InternalMessageInfo

func (m *DelCasesRequest) GetCaseUuids() []string {
	if m != nil {
		return m.CaseUuids
	}
	return nil
}

func init() {
	proto.RegisterEnum("org.covid19.api.CaseState", CaseState_name, CaseState_value)
	proto.RegisterEnum("org.covid19.api.InfectionSource", InfectionSource_name, InfectionSource_value)
	proto.RegisterType((*ExistingCaseDetail)(nil), "org.covid19.api.ExistingCaseDetail")
	proto.RegisterType((*NewCaseDetail)(nil), "org.covid19.api.NewCaseDetail")
	proto.RegisterType((*GetCasesRequest)(nil), "org.covid19.api.GetCasesRequest")
	proto.RegisterType((*GetCasesResponse)(nil), "org.covid19.api.GetCasesResponse")
	proto.RegisterType((*AddCasesRequest)(nil), "org.covid19.api.AddCasesRequest")
	proto.RegisterType((*PutCasesRequest)(nil), "org.covid19.api.PutCasesRequest")
	proto.RegisterType((*DelCasesRequest)(nil), "org.covid19.api.DelCasesRequest")
}

func init() {
	proto.RegisterFile("case.def.proto", fileDescriptor_c687d06fd30aa5ff)
}

var fileDescriptor_c687d06fd30aa5ff = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0xc1, 0x4e, 0xdb, 0x4a,
	0x14, 0xc5, 0x41, 0x40, 0x7c, 0x1d, 0x13, 0x33, 0x12, 0xc8, 0x0a, 0x8f, 0xd7, 0x88, 0x6e, 0x10,
	0x0b, 0x43, 0xd3, 0x76, 0x11, 0x75, 0x81, 0x20, 0x76, 0x83, 0xd5, 0xe0, 0x58, 0xe3, 0xd0, 0x2e,
	0x23, 0x63, 0x4f, 0x2c, 0x4b, 0x89, 0xc7, 0xf5, 0x8c, 0xdb, 0x7e, 0x43, 0xbf, 0xa1, 0xff, 0xd4,
	0xff, 0xe9, 0xaa, 0x1a, 0x3b, 0x26, 0x09, 0x41, 0x42, 0x48, 0x55, 0x57, 0x5d, 0xce, 0xf5, 0x39,
	0xc7, 0x67, 0xee, 0x3d, 0x73, 0x61, 0x37, 0xf0, 0x19, 0x31, 0x42, 0x32, 0x31, 0xd2, 0x8c, 0x72,
	0x8a, 0x9a, 0x34, 0x8b, 0x8c, 0x80, 0x7e, 0x89, 0xc3, 0x57, 0x5d, 0xc3, 0x4f, 0xe3, 0xd6, 0x8b,
	0x88, 0xd2, 0x68, 0x4a, 0xce, 0x8a, 0xcf, 0x77, 0xf9, 0xe4, 0x8c, 0xc7, 0x33, 0xc2, 0xb8, 0x3f,
	0x4b, 0x4b, 0x46, 0xab, 0x11, 0xd0, 0xd9, 0x8c, 0x26, 0xf3, 0x93, 0x1a, 0x11, 0xba, 0x90, 0x3b,
	0xfe, 0xb1, 0x09, 0xc8, 0xfa, 0x16, 0x33, 0x1e, 0x27, 0x51, 0xcf, 0x67, 0xc4, 0x24, 0xdc, 0x8f,
	0xa7, 0xe8, 0x10, 0x64, 0xf1, 0xdf, 0x71, 0x9e, 0xc7, 0xa1, 0x2e, 0xb5, 0xa5, 0x13, 0x19, 0xd7,
	0x45, 0xe1, 0x36, 0x8f, 0x43, 0x74, 0x04, 0x90, 0xfa, 0x3c, 0x26, 0x09, 0x1f, 0xc7, 0xa1, 0x5e,
	0x2b, 0xbe, 0xca, 0xf3, 0x8a, 0x1d, 0xa2, 0x0b, 0x50, 0x33, 0x92, 0xd2, 0x8c, 0x93, 0x70, 0x2c,
	0xbc, 0xe8, 0x9b, 0x6d, 0xe9, 0x44, 0xe9, 0xb4, 0x8c, 0xd2, 0xa8, 0x51, 0x19, 0x35, 0x46, 0x95,
	0x51, 0xdc, 0xa8, 0x08, 0xa2, 0x84, 0xce, 0x61, 0x8b, 0x71, 0x9f, 0x13, 0x5d, 0x69, 0x4b, 0x27,
	0xbb, 0x9d, 0x96, 0xf1, 0xe0, 0xca, 0x86, 0x30, 0xea, 0x09, 0x04, 0x2e, 0x81, 0xe8, 0x02, 0x20,
	0x4e, 0x26, 0x24, 0xe0, 0x63, 0x96, 0x05, 0x7a, 0xa3, 0xa0, 0xb5, 0xd7, 0x68, 0x76, 0x01, 0x89,
	0x69, 0xe2, 0xd1, 0x3c, 0x0b, 0x08, 0x96, 0x4b, 0x8e, 0x97, 0x05, 0xa8, 0x0f, 0xbb, 0x89, 0x3f,
	0x23, 0xe1, 0x78, 0x4a, 0x03, 0x5f, 0x40, 0xf4, 0xfd, 0xc2, 0xf4, 0xff, 0x6b, 0x22, 0x8e, 0x80,
	0x0d, 0xe6, 0xa8, 0xeb, 0x0d, 0xac, 0x26, 0xcb, 0x05, 0x74, 0x09, 0x8d, 0x28, 0x65, 0x0b, 0x99,
	0x83, 0x42, 0xe6, 0xbf, 0x35, 0x99, 0xbe, 0xeb, 0x2d, 0x89, 0x28, 0x51, 0xca, 0xaa, 0xe3, 0x15,
	0x40, 0xbd, 0xa2, 0x1f, 0xff, 0xaa, 0x81, 0xea, 0x90, 0xaf, 0x4b, 0x93, 0xf9, 0xd7, 0xfc, 0xbf,
	0xd6, 0xfc, 0x9f, 0x35, 0x68, 0xf6, 0x09, 0x17, 0x17, 0x66, 0x98, 0x7c, 0xce, 0x09, 0xe3, 0x8f,
	0x78, 0x95, 0xfe, 0x8c, 0xd7, 0xda, 0xb3, 0xbd, 0xa2, 0x0e, 0x6c, 0x17, 0x13, 0x60, 0xba, 0xd2,
	0xde, 0x7c, 0x62, 0x56, 0x73, 0x24, 0xea, 0x02, 0x30, 0xee, 0x67, 0xbc, 0x0c, 0xc7, 0xfe, 0x93,
	0xe1, 0x90, 0x0b, 0x74, 0x91, 0x8c, 0xb7, 0x50, 0x27, 0xc9, 0x3c, 0x55, 0x07, 0x4f, 0x12, 0x77,
	0x48, 0x52, 0x04, 0x6a, 0xa5, 0xa3, 0xdf, 0x25, 0xd0, 0x16, 0x1d, 0x65, 0x29, 0x4d, 0x18, 0x41,
	0xef, 0x44, 0xa2, 0xa3, 0x38, 0x59, 0x6e, 0xe7, 0xe1, 0xda, 0x55, 0xdc, 0x7b, 0x08, 0x5e, 0x82,
	0xa3, 0x2e, 0x6c, 0x89, 0xbd, 0x54, 0xb6, 0x40, 0xe9, 0xbc, 0x5c, 0xe3, 0xad, 0x2f, 0x37, 0x5c,
	0x32, 0x8e, 0xfb, 0xd0, 0xbc, 0x0c, 0xc3, 0x95, 0xe9, 0xbe, 0xa9, 0xd4, 0xa4, 0x42, 0xed, 0x91,
	0xa1, 0x2e, 0xbf, 0xc5, 0x4a, 0x68, 0x00, 0x4d, 0x37, 0x5f, 0x8d, 0x49, 0x77, 0x55, 0xe8, 0x39,
	0xb6, 0xce, 0xa1, 0x69, 0x92, 0xe9, 0x8a, 0xda, 0x11, 0xc0, 0xfd, 0x36, 0x2e, 0x25, 0x65, 0x2c,
	0x57, 0xeb, 0x98, 0x9d, 0x62, 0x90, 0xef, 0x07, 0x8d, 0x14, 0xd8, 0xb9, 0x75, 0x3e, 0x38, 0xc3,
	0x4f, 0x8e, 0xb6, 0x81, 0x9a, 0xa0, 0xdc, 0x3a, 0xa6, 0xed, 0xf5, 0x06, 0x43, 0xcf, 0x32, 0x35,
	0x09, 0xa9, 0x20, 0xf7, 0x86, 0xce, 0x7b, 0x1b, 0xdf, 0x58, 0xa6, 0xa6, 0x88, 0x23, 0xb6, 0x7a,
	0xc3, 0x8f, 0x16, 0xb6, 0x4c, 0xad, 0x81, 0x64, 0xd8, 0x32, 0xad, 0xcb, 0xd1, 0xb5, 0xa6, 0x9e,
	0x5a, 0xd0, 0x7c, 0xf0, 0x62, 0x51, 0x03, 0xea, 0xe6, 0xf0, 0xc6, 0xf2, 0x46, 0x76, 0x4f, 0xdb,
	0x40, 0x7b, 0xa0, 0xda, 0xce, 0x68, 0x30, 0xb6, 0x6f, 0xdc, 0x21, 0x1e, 0x15, 0xe2, 0x7b, 0xa0,
	0x7a, 0xd7, 0xb6, 0xbb, 0x28, 0xd5, 0xae, 0x0e, 0xae, 0x90, 0xb0, 0x66, 0x27, 0x9c, 0x64, 0x13,
	0x3f, 0x20, 0xae, 0x08, 0x8a, 0x2b, 0xdd, 0x6d, 0x17, 0x89, 0x79, 0xfd, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x26, 0x63, 0xf3, 0x10, 0xde, 0x06, 0x00, 0x00,
}
