// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flight.def.proto

package org_covid19_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlightDetail struct {
	FlightNum            string               `protobuf:"bytes,1,opt,name=flight_num,json=flightNum,proto3" json:"flight_num,omitempty"`
	IataCode             string               `protobuf:"bytes,2,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	IcaoCode             string               `protobuf:"bytes,3,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	DepDate              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=dep_date,json=depDate,proto3" json:"dep_date,omitempty"`
	ArrDate              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=arr_date,json=arrDate,proto3" json:"arr_date,omitempty"`
	DepAirport           string               `protobuf:"bytes,11,opt,name=dep_airport,json=depAirport,proto3" json:"dep_airport,omitempty"`
	ArrAirport           string               `protobuf:"bytes,12,opt,name=arr_airport,json=arrAirport,proto3" json:"arr_airport,omitempty"`
	AffectedRows         []uint32             `protobuf:"varint,21,rep,packed,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FlightDetail) Reset()         { *m = FlightDetail{} }
func (m *FlightDetail) String() string { return proto.CompactTextString(m) }
func (*FlightDetail) ProtoMessage()    {}
func (*FlightDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb6d24b61a41e34, []int{0}
}

func (m *FlightDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightDetail.Unmarshal(m, b)
}
func (m *FlightDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightDetail.Marshal(b, m, deterministic)
}
func (m *FlightDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightDetail.Merge(m, src)
}
func (m *FlightDetail) XXX_Size() int {
	return xxx_messageInfo_FlightDetail.Size(m)
}
func (m *FlightDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightDetail.DiscardUnknown(m)
}

var xxx_messageInfo_FlightDetail proto.InternalMessageInfo

func (m *FlightDetail) GetFlightNum() string {
	if m != nil {
		return m.FlightNum
	}
	return ""
}

func (m *FlightDetail) GetIataCode() string {
	if m != nil {
		return m.IataCode
	}
	return ""
}

func (m *FlightDetail) GetIcaoCode() string {
	if m != nil {
		return m.IcaoCode
	}
	return ""
}

func (m *FlightDetail) GetDepDate() *timestamp.Timestamp {
	if m != nil {
		return m.DepDate
	}
	return nil
}

func (m *FlightDetail) GetArrDate() *timestamp.Timestamp {
	if m != nil {
		return m.ArrDate
	}
	return nil
}

func (m *FlightDetail) GetDepAirport() string {
	if m != nil {
		return m.DepAirport
	}
	return ""
}

func (m *FlightDetail) GetArrAirport() string {
	if m != nil {
		return m.ArrAirport
	}
	return ""
}

func (m *FlightDetail) GetAffectedRows() []uint32 {
	if m != nil {
		return m.AffectedRows
	}
	return nil
}

// GetFlightsRequest describes request payload for querying affected flights match specific criteria
type GetFlightsRequest struct {
	FlightNum            string   `protobuf:"bytes,1,opt,name=flight_num,json=flightNum,proto3" json:"flight_num,omitempty"`
	DepDate              uint32   `protobuf:"varint,4,opt,name=dep_date,json=depDate,proto3" json:"dep_date,omitempty"`
	DepAirport           string   `protobuf:"bytes,11,opt,name=dep_airport,json=depAirport,proto3" json:"dep_airport,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlightsRequest) Reset()         { *m = GetFlightsRequest{} }
func (m *GetFlightsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlightsRequest) ProtoMessage()    {}
func (*GetFlightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb6d24b61a41e34, []int{1}
}

func (m *GetFlightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlightsRequest.Unmarshal(m, b)
}
func (m *GetFlightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlightsRequest.Marshal(b, m, deterministic)
}
func (m *GetFlightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlightsRequest.Merge(m, src)
}
func (m *GetFlightsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlightsRequest.Size(m)
}
func (m *GetFlightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlightsRequest proto.InternalMessageInfo

func (m *GetFlightsRequest) GetFlightNum() string {
	if m != nil {
		return m.FlightNum
	}
	return ""
}

func (m *GetFlightsRequest) GetDepDate() uint32 {
	if m != nil {
		return m.DepDate
	}
	return 0
}

func (m *GetFlightsRequest) GetDepAirport() string {
	if m != nil {
		return m.DepAirport
	}
	return ""
}

// GetFlightsResponse describes response payload for matched flights
type GetFlightsResponse struct {
	Pagination           *Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Flights              []*FlightDetail `protobuf:"bytes,11,rep,name=flights,proto3" json:"flights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetFlightsResponse) Reset()         { *m = GetFlightsResponse{} }
func (m *GetFlightsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFlightsResponse) ProtoMessage()    {}
func (*GetFlightsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb6d24b61a41e34, []int{2}
}

func (m *GetFlightsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlightsResponse.Unmarshal(m, b)
}
func (m *GetFlightsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlightsResponse.Marshal(b, m, deterministic)
}
func (m *GetFlightsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlightsResponse.Merge(m, src)
}
func (m *GetFlightsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFlightsResponse.Size(m)
}
func (m *GetFlightsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlightsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlightsResponse proto.InternalMessageInfo

func (m *GetFlightsResponse) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetFlightsResponse) GetFlights() []*FlightDetail {
	if m != nil {
		return m.Flights
	}
	return nil
}

// AddFlightsRequest describes request payload for adding affected flights
type AddFlightsRequest struct {
	Flights              []*FlightDetail `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddFlightsRequest) Reset()         { *m = AddFlightsRequest{} }
func (m *AddFlightsRequest) String() string { return proto.CompactTextString(m) }
func (*AddFlightsRequest) ProtoMessage()    {}
func (*AddFlightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb6d24b61a41e34, []int{3}
}

func (m *AddFlightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFlightsRequest.Unmarshal(m, b)
}
func (m *AddFlightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFlightsRequest.Marshal(b, m, deterministic)
}
func (m *AddFlightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFlightsRequest.Merge(m, src)
}
func (m *AddFlightsRequest) XXX_Size() int {
	return xxx_messageInfo_AddFlightsRequest.Size(m)
}
func (m *AddFlightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFlightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFlightsRequest proto.InternalMessageInfo

func (m *AddFlightsRequest) GetFlights() []*FlightDetail {
	if m != nil {
		return m.Flights
	}
	return nil
}

// DelFlightsRequest describes request payload for deleting affected flights
type DelFlightsRequest struct {
	Flights              []*DelFlightsRequest_FlightIdentifier `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DelFlightsRequest) Reset()         { *m = DelFlightsRequest{} }
func (m *DelFlightsRequest) String() string { return proto.CompactTextString(m) }
func (*DelFlightsRequest) ProtoMessage()    {}
func (*DelFlightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb6d24b61a41e34, []int{4}
}

func (m *DelFlightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFlightsRequest.Unmarshal(m, b)
}
func (m *DelFlightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFlightsRequest.Marshal(b, m, deterministic)
}
func (m *DelFlightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFlightsRequest.Merge(m, src)
}
func (m *DelFlightsRequest) XXX_Size() int {
	return xxx_messageInfo_DelFlightsRequest.Size(m)
}
func (m *DelFlightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFlightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelFlightsRequest proto.InternalMessageInfo

func (m *DelFlightsRequest) GetFlights() []*DelFlightsRequest_FlightIdentifier {
	if m != nil {
		return m.Flights
	}
	return nil
}

type DelFlightsRequest_FlightIdentifier struct {
	FlightNum            string   `protobuf:"bytes,1,opt,name=flight_num,json=flightNum,proto3" json:"flight_num,omitempty"`
	DepDate              uint32   `protobuf:"varint,2,opt,name=dep_date,json=depDate,proto3" json:"dep_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelFlightsRequest_FlightIdentifier) Reset()         { *m = DelFlightsRequest_FlightIdentifier{} }
func (m *DelFlightsRequest_FlightIdentifier) String() string { return proto.CompactTextString(m) }
func (*DelFlightsRequest_FlightIdentifier) ProtoMessage()    {}
func (*DelFlightsRequest_FlightIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb6d24b61a41e34, []int{4, 0}
}

func (m *DelFlightsRequest_FlightIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFlightsRequest_FlightIdentifier.Unmarshal(m, b)
}
func (m *DelFlightsRequest_FlightIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFlightsRequest_FlightIdentifier.Marshal(b, m, deterministic)
}
func (m *DelFlightsRequest_FlightIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFlightsRequest_FlightIdentifier.Merge(m, src)
}
func (m *DelFlightsRequest_FlightIdentifier) XXX_Size() int {
	return xxx_messageInfo_DelFlightsRequest_FlightIdentifier.Size(m)
}
func (m *DelFlightsRequest_FlightIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFlightsRequest_FlightIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_DelFlightsRequest_FlightIdentifier proto.InternalMessageInfo

func (m *DelFlightsRequest_FlightIdentifier) GetFlightNum() string {
	if m != nil {
		return m.FlightNum
	}
	return ""
}

func (m *DelFlightsRequest_FlightIdentifier) GetDepDate() uint32 {
	if m != nil {
		return m.DepDate
	}
	return 0
}

func init() {
	proto.RegisterType((*FlightDetail)(nil), "org.covid19.api.FlightDetail")
	proto.RegisterType((*GetFlightsRequest)(nil), "org.covid19.api.GetFlightsRequest")
	proto.RegisterType((*GetFlightsResponse)(nil), "org.covid19.api.GetFlightsResponse")
	proto.RegisterType((*AddFlightsRequest)(nil), "org.covid19.api.AddFlightsRequest")
	proto.RegisterType((*DelFlightsRequest)(nil), "org.covid19.api.DelFlightsRequest")
	proto.RegisterType((*DelFlightsRequest_FlightIdentifier)(nil), "org.covid19.api.DelFlightsRequest.FlightIdentifier")
}

func init() {
	proto.RegisterFile("flight.def.proto", fileDescriptor_5fb6d24b61a41e34)
}

var fileDescriptor_5fb6d24b61a41e34 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x13, 0xa0, 0xcd, 0x38, 0x11, 0x8d, 0x05, 0x92, 0x49, 0x55, 0x35, 0x0a, 0x97, 0x9c,
	0xb6, 0x22, 0x15, 0x42, 0x88, 0x53, 0x4b, 0x04, 0x42, 0x2a, 0x28, 0xb2, 0xb8, 0x47, 0x53, 0xef,
	0xd8, 0xac, 0x14, 0x7b, 0x96, 0xf5, 0x86, 0xbe, 0x03, 0x4f, 0xc3, 0x03, 0xf0, 0x70, 0xc8, 0xbb,
	0x71, 0x71, 0x9d, 0x43, 0xd4, 0xa3, 0xe7, 0xfb, 0xf5, 0xec, 0xc0, 0x49, 0xb6, 0x51, 0xf9, 0x0f,
	0x2b, 0x24, 0x65, 0x42, 0x1b, 0xb6, 0x1c, 0x3d, 0x67, 0x93, 0x8b, 0x94, 0x7f, 0x29, 0xf9, 0xe6,
	0xbd, 0x40, 0xad, 0x26, 0xe7, 0x39, 0x73, 0xbe, 0xa1, 0x0b, 0x07, 0xdf, 0x6e, 0xb3, 0x0b, 0xab,
	0x0a, 0xaa, 0x2c, 0x16, 0xda, 0x2b, 0x26, 0xc3, 0x94, 0x8b, 0x82, 0x4b, 0xff, 0x35, 0xfb, 0xdb,
	0x83, 0xe1, 0x27, 0x67, 0xba, 0x24, 0x8b, 0x6a, 0x13, 0x9d, 0x01, 0xf8, 0x90, 0x75, 0xb9, 0x2d,
	0xe2, 0x60, 0x1a, 0xcc, 0x07, 0xc9, 0xc0, 0x4f, 0xbe, 0x6d, 0x8b, 0xe8, 0x14, 0x06, 0x0a, 0x2d,
	0xae, 0x53, 0x96, 0x14, 0xf7, 0x1c, 0x7a, 0x5c, 0x0f, 0x3e, 0xb2, 0x24, 0x07, 0xa6, 0xc8, 0x1e,
	0xec, 0xef, 0xc0, 0x14, 0xd9, 0x81, 0x6f, 0xe1, 0x58, 0x92, 0x5e, 0x4b, 0xb4, 0x14, 0x3f, 0x99,
	0x06, 0xf3, 0x70, 0x31, 0x11, 0xbe, 0xab, 0x68, 0xba, 0x8a, 0xef, 0x4d, 0xd7, 0xe4, 0x48, 0x92,
	0x5e, 0xa2, 0x75, 0x32, 0x34, 0xc6, 0xcb, 0x9e, 0x1e, 0x96, 0xa1, 0x31, 0x4e, 0x76, 0x0e, 0x61,
	0x9d, 0x86, 0xca, 0x68, 0x36, 0x36, 0x0e, 0x5d, 0x19, 0x90, 0xa4, 0xaf, 0xfc, 0xa4, 0x26, 0xd4,
	0xbe, 0x0d, 0x61, 0xe8, 0x09, 0x68, 0x4c, 0x43, 0x78, 0x0d, 0x23, 0xcc, 0x32, 0x4a, 0x2d, 0xc9,
	0xb5, 0xe1, 0xbb, 0x2a, 0x7e, 0x39, 0xed, 0xcf, 0x47, 0xc9, 0xb0, 0x19, 0x26, 0x7c, 0x57, 0xcd,
	0x4a, 0x18, 0x7f, 0x26, 0xeb, 0x17, 0x58, 0x25, 0xf4, 0x73, 0x4b, 0x95, 0x3d, 0xb4, 0xc2, 0x57,
	0x9d, 0x45, 0x8c, 0xfe, 0xff, 0xec, 0xa1, 0xd6, 0xb3, 0xdf, 0x01, 0x44, 0xed, 0xc0, 0x4a, 0x73,
	0x59, 0x51, 0xf4, 0x01, 0x40, 0x63, 0xae, 0x4a, 0xb4, 0x8a, 0x4b, 0x97, 0x18, 0x2e, 0x4e, 0x45,
	0xe7, 0x34, 0xc4, 0xea, 0x9e, 0x92, 0xb4, 0xe8, 0xd1, 0x3b, 0x38, 0xf2, 0xe5, 0xaa, 0x38, 0x9c,
	0xf6, 0xe7, 0xe1, 0xe2, 0x6c, 0x4f, 0xd9, 0xbe, 0x90, 0xa4, 0x61, 0xcf, 0x6e, 0x60, 0x7c, 0x25,
	0x65, 0xe7, 0xe7, 0x5b, 0x6e, 0xc1, 0xa3, 0xdc, 0xfe, 0x04, 0x30, 0x5e, 0xd2, 0xa6, 0x63, 0xf7,
	0xb5, 0x6b, 0x77, 0xb9, 0x67, 0xb7, 0x27, 0xda, 0x05, 0x7c, 0x91, 0x54, 0x5a, 0x95, 0x29, 0x32,
	0xf7, 0x21, 0x93, 0x1b, 0x38, 0xe9, 0x82, 0x8f, 0x79, 0xae, 0xde, 0x83, 0xe7, 0xba, 0x8e, 0xaf,
	0x5f, 0xec, 0xdc, 0x4a, 0x4b, 0x26, 0xc3, 0x94, 0x56, 0xf5, 0x49, 0xae, 0x82, 0xdb, 0x67, 0xee,
	0x36, 0x2f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x00, 0x99, 0x89, 0xb1, 0x03, 0x00, 0x00,
}
