// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geo.def.proto

package org_covid19_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CityLocation describes location information with text-based names
type CityLocation struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode           string   `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityLocation) Reset()         { *m = CityLocation{} }
func (m *CityLocation) String() string { return proto.CompactTextString(m) }
func (*CityLocation) ProtoMessage()    {}
func (*CityLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1446070098fba2b, []int{0}
}

func (m *CityLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityLocation.Unmarshal(m, b)
}
func (m *CityLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityLocation.Marshal(b, m, deterministic)
}
func (m *CityLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityLocation.Merge(m, src)
}
func (m *CityLocation) XXX_Size() int {
	return xxx_messageInfo_CityLocation.Size(m)
}
func (m *CityLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_CityLocation.DiscardUnknown(m)
}

var xxx_messageInfo_CityLocation proto.InternalMessageInfo

func (m *CityLocation) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CityLocation) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CityLocation) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CityLocation) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

// GPSLocation describes location information with GPS coordinates
type GPSLocation struct {
	GeoLat               float64  `protobuf:"fixed64,1,opt,name=geo_lat,json=geoLat,proto3" json:"geo_lat,omitempty"`
	GeoLng               float64  `protobuf:"fixed64,2,opt,name=geo_lng,json=geoLng,proto3" json:"geo_lng,omitempty"`
	PrecisionRad         uint64   `protobuf:"varint,3,opt,name=precision_rad,json=precisionRad,proto3" json:"precision_rad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPSLocation) Reset()         { *m = GPSLocation{} }
func (m *GPSLocation) String() string { return proto.CompactTextString(m) }
func (*GPSLocation) ProtoMessage()    {}
func (*GPSLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1446070098fba2b, []int{1}
}

func (m *GPSLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPSLocation.Unmarshal(m, b)
}
func (m *GPSLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPSLocation.Marshal(b, m, deterministic)
}
func (m *GPSLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPSLocation.Merge(m, src)
}
func (m *GPSLocation) XXX_Size() int {
	return xxx_messageInfo_GPSLocation.Size(m)
}
func (m *GPSLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_GPSLocation.DiscardUnknown(m)
}

var xxx_messageInfo_GPSLocation proto.InternalMessageInfo

func (m *GPSLocation) GetGeoLat() float64 {
	if m != nil {
		return m.GeoLat
	}
	return 0
}

func (m *GPSLocation) GetGeoLng() float64 {
	if m != nil {
		return m.GeoLng
	}
	return 0
}

func (m *GPSLocation) GetPrecisionRad() uint64 {
	if m != nil {
		return m.PrecisionRad
	}
	return 0
}

func init() {
	proto.RegisterType((*CityLocation)(nil), "org.covid19.api.CityLocation")
	proto.RegisterType((*GPSLocation)(nil), "org.covid19.api.GPSLocation")
}

func init() {
	proto.RegisterFile("geo.def.proto", fileDescriptor_b1446070098fba2b)
}

var fileDescriptor_b1446070098fba2b = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x46, 0x59, 0x5d, 0xb6, 0x38, 0x6d, 0x11, 0x03, 0x6a, 0x6e, 0x4a, 0xbd, 0x78, 0x5a, 0x10,
	0x4f, 0x5e, 0xdb, 0x43, 0x11, 0x7a, 0x58, 0xd6, 0x1f, 0xb0, 0xc4, 0x64, 0x1a, 0x02, 0x25, 0x5f,
	0x48, 0xa7, 0xc2, 0xfe, 0x7b, 0x31, 0xb6, 0x7b, 0x9b, 0x79, 0xef, 0xf0, 0xe0, 0xa3, 0xa5, 0x67,
	0xb4, 0x8e, 0xf7, 0x6d, 0xca, 0x10, 0xa8, 0x5b, 0x64, 0xdf, 0x5a, 0xfc, 0x04, 0xf7, 0xf6, 0xd1,
	0x9a, 0x14, 0x56, 0x27, 0x5a, 0x6c, 0x82, 0x8c, 0x3b, 0x58, 0x23, 0x01, 0x51, 0x69, 0x9a, 0x59,
	0x9c, 0xa2, 0xe4, 0x51, 0x57, 0xcf, 0xd5, 0xeb, 0x4d, 0x7f, 0x79, 0xd5, 0x03, 0x35, 0x99, 0x7d,
	0x40, 0xd4, 0x57, 0x45, 0x9c, 0x3f, 0xa5, 0xa8, 0xb6, 0x41, 0x46, 0x7d, 0x5d, 0x68, 0xb9, 0xd5,
	0x13, 0xcd, 0x13, 0x8e, 0x62, 0x0e, 0x83, 0x85, 0x63, 0x5d, 0x17, 0x45, 0xff, 0x68, 0x03, 0xc7,
	0x2b, 0x47, 0xf3, 0x6d, 0xf7, 0x35, 0x55, 0x1f, 0x69, 0xe6, 0x19, 0xc3, 0xc1, 0x48, 0xa9, 0x56,
	0x7d, 0xe3, 0x19, 0x3b, 0x23, 0x93, 0x88, 0xbe, 0x54, 0xcf, 0x22, 0x7a, 0xf5, 0x42, 0xcb, 0x94,
	0xd9, 0x86, 0x63, 0x40, 0x1c, 0xb2, 0x71, 0x25, 0x5f, 0xf7, 0x8b, 0x09, 0xf6, 0xc6, 0xad, 0xef,
	0xd7, 0x77, 0x5b, 0xc6, 0x67, 0x14, 0xce, 0x7b, 0x63, 0xb9, 0xfb, 0x9b, 0xa0, 0xab, 0xbe, 0x9b,
	0xb2, 0xc5, 0xfb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x06, 0x1d, 0x67, 0x1c, 0x01, 0x00,
	0x00,
}
