// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geo.def.proto

package org_covid19_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NamedLocation describes location information with text-based names
type NamedLocation struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode           string   `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedLocation) Reset()         { *m = NamedLocation{} }
func (m *NamedLocation) String() string { return proto.CompactTextString(m) }
func (*NamedLocation) ProtoMessage()    {}
func (*NamedLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1446070098fba2b, []int{0}
}

func (m *NamedLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedLocation.Unmarshal(m, b)
}
func (m *NamedLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedLocation.Marshal(b, m, deterministic)
}
func (m *NamedLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedLocation.Merge(m, src)
}
func (m *NamedLocation) XXX_Size() int {
	return xxx_messageInfo_NamedLocation.Size(m)
}
func (m *NamedLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedLocation.DiscardUnknown(m)
}

var xxx_messageInfo_NamedLocation proto.InternalMessageInfo

func (m *NamedLocation) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *NamedLocation) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *NamedLocation) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *NamedLocation) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

// GPSLocation describes location information with GPS coordinates
type GPSLocation struct {
	GeoLat               float64  `protobuf:"fixed64,1,opt,name=geo_lat,json=geoLat,proto3" json:"geo_lat,omitempty"`
	GeoLng               float64  `protobuf:"fixed64,2,opt,name=geo_lng,json=geoLng,proto3" json:"geo_lng,omitempty"`
	PrecisionRad         uint64   `protobuf:"varint,3,opt,name=precision_rad,json=precisionRad,proto3" json:"precision_rad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPSLocation) Reset()         { *m = GPSLocation{} }
func (m *GPSLocation) String() string { return proto.CompactTextString(m) }
func (*GPSLocation) ProtoMessage()    {}
func (*GPSLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1446070098fba2b, []int{1}
}

func (m *GPSLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPSLocation.Unmarshal(m, b)
}
func (m *GPSLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPSLocation.Marshal(b, m, deterministic)
}
func (m *GPSLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPSLocation.Merge(m, src)
}
func (m *GPSLocation) XXX_Size() int {
	return xxx_messageInfo_GPSLocation.Size(m)
}
func (m *GPSLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_GPSLocation.DiscardUnknown(m)
}

var xxx_messageInfo_GPSLocation proto.InternalMessageInfo

func (m *GPSLocation) GetGeoLat() float64 {
	if m != nil {
		return m.GeoLat
	}
	return 0
}

func (m *GPSLocation) GetGeoLng() float64 {
	if m != nil {
		return m.GeoLng
	}
	return 0
}

func (m *GPSLocation) GetPrecisionRad() uint64 {
	if m != nil {
		return m.PrecisionRad
	}
	return 0
}

func init() {
	proto.RegisterType((*NamedLocation)(nil), "org.covid19.api.NamedLocation")
	proto.RegisterType((*GPSLocation)(nil), "org.covid19.api.GPSLocation")
}

func init() {
	proto.RegisterFile("geo.def.proto", fileDescriptor_b1446070098fba2b)
}

var fileDescriptor_b1446070098fba2b = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x46, 0x59, 0x5d, 0xb6, 0x38, 0x75, 0x11, 0x03, 0x6a, 0x6e, 0x4a, 0xbd, 0x78, 0x5a, 0x10,
	0x4f, 0x5e, 0xeb, 0xa1, 0x08, 0x45, 0x96, 0xf5, 0x07, 0x2c, 0x63, 0x32, 0x0d, 0x81, 0x9a, 0x2f,
	0xa4, 0xb1, 0xd0, 0x7f, 0x2f, 0xc6, 0x76, 0x6f, 0x33, 0xef, 0x1d, 0x1e, 0x7c, 0xd4, 0x3a, 0x41,
	0x67, 0x65, 0xd3, 0xc5, 0x84, 0x0c, 0x75, 0x85, 0xe4, 0x3a, 0x83, 0xbd, 0xb7, 0xcf, 0xaf, 0x1d,
	0x47, 0xbf, 0xd8, 0x53, 0xfb, 0xc1, 0xdf, 0x62, 0xd7, 0x30, 0x9c, 0x3d, 0x82, 0xd2, 0x34, 0x33,
	0xf8, 0x09, 0x39, 0x1d, 0x74, 0xf5, 0x50, 0x3d, 0x5d, 0x0c, 0xa7, 0x57, 0xdd, 0x52, 0x93, 0xc4,
	0x79, 0x04, 0x7d, 0x56, 0xc4, 0xf1, 0x53, 0x8a, 0x6a, 0xe3, 0xf3, 0x41, 0x9f, 0x17, 0x5a, 0x6e,
	0x75, 0x4f, 0xf3, 0x88, 0x5d, 0xe6, 0xed, 0x68, 0x60, 0x45, 0xd7, 0x45, 0xd1, 0x3f, 0x7a, 0x83,
	0x95, 0x85, 0xa5, 0xf9, 0xaa, 0xff, 0x9c, 0xaa, 0x77, 0x34, 0x73, 0x82, 0x71, 0xcb, 0xb9, 0x54,
	0xab, 0xa1, 0x71, 0x82, 0x35, 0xe7, 0x49, 0x04, 0x57, 0xaa, 0x47, 0x11, 0x9c, 0x7a, 0xa4, 0x36,
	0x26, 0x31, 0x7e, 0xe7, 0x11, 0xc6, 0xc4, 0xb6, 0xe4, 0xeb, 0xe1, 0x72, 0x82, 0x03, 0xdb, 0xe5,
	0xcd, 0xf2, 0x7a, 0x25, 0x78, 0x0f, 0x59, 0xd2, 0x86, 0x8d, 0xf4, 0x7f, 0x1b, 0xf4, 0xd5, 0x57,
	0x53, 0xc6, 0x78, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x56, 0x0f, 0x8b, 0x62, 0x1d, 0x01, 0x00,
	0x00,
}
