// Code generated by protoc-gen-go. DO NOT EDIT.
// source: public.svc.proto

package org_covid19_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("public.svc.proto", fileDescriptor_95a0a6b137d15da1)
}

var fileDescriptor_95a0a6b137d15da1 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xcd, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xd9, 0x8b, 0x48, 0x04, 0x77, 0x0d, 0xe2, 0x21, 0x82, 0xf8, 0x71, 0x9f, 0x45, 0x3d,
	0x79, 0xad, 0x1f, 0x8b, 0x27, 0xeb, 0x8a, 0xde, 0xd3, 0x74, 0x5a, 0x03, 0xd1, 0x89, 0xf9, 0xa8,
	0xf4, 0x6f, 0xf7, 0x22, 0x6d, 0x5a, 0x58, 0x56, 0xe9, 0xf5, 0xfd, 0xde, 0xcc, 0x7b, 0x8f, 0x2d,
	0x6c, 0x2c, 0x8c, 0x56, 0xe0, 0x1b, 0x05, 0xd6, 0x51, 0x20, 0x3e, 0x27, 0x57, 0x83, 0xa2, 0x46,
	0x97, 0x97, 0x37, 0x20, 0xad, 0x16, 0xc7, 0x35, 0x51, 0x6d, 0x70, 0xd9, 0xe3, 0x22, 0x56, 0x4b,
	0xfc, 0xb0, 0xa1, 0x4d, 0x6e, 0x71, 0xb2, 0x0d, 0xbf, 0x9d, 0xb4, 0x16, 0x9d, 0x1f, 0xf8, 0x5c,
	0x49, 0x8f, 0x1e, 0x4a, 0xac, 0x06, 0xe1, 0xa0, 0x32, 0xba, 0x7e, 0x0f, 0x1b, 0xd2, 0xd5, 0xcf,
	0x8c, 0xed, 0xe5, 0x7d, 0x8d, 0xe7, 0x88, 0xae, 0xe5, 0x77, 0x6c, 0xff, 0xd1, 0xbf, 0xa0, 0x6b,
	0xb4, 0xc2, 0x35, 0xca, 0xb2, 0xe5, 0x47, 0x90, 0x62, 0x60, 0x8c, 0x81, 0xfb, 0xae, 0x83, 0x10,
	0x7f, 0xf4, 0x8c, 0xc8, 0xbc, 0x49, 0x13, 0x91, 0x3f, 0xb1, 0xdd, 0x15, 0x86, 0xdb, 0x2e, 0x9e,
	0x9f, 0xc2, 0xd6, 0x28, 0x18, 0xd1, 0x1a, 0xbf, 0x22, 0xfa, 0x20, 0xce, 0x26, 0x1c, 0xde, 0xd2,
	0xa7, 0x47, 0xfe, 0xca, 0xd8, 0x0a, 0xc3, 0x43, 0xaa, 0xcf, 0xcf, 0xff, 0x3b, 0x18, 0xe0, 0xf8,
	0xf4, 0x62, 0xd2, 0x93, 0xde, 0x66, 0x87, 0xd9, 0x62, 0x63, 0x7c, 0xde, 0x0d, 0xc9, 0x67, 0xc5,
	0x4e, 0xbf, 0xe8, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xd7, 0x38, 0x4c, 0xa0, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PublicQueryClient is the client API for PublicQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublicQueryClient interface {
	IsServiceReady(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	GetCases(ctx context.Context, in *GetCasesRequest, opts ...grpc.CallOption) (*GetCasesResponse, error)
	GetFlights(ctx context.Context, in *GetFlightsRequest, opts ...grpc.CallOption) (*GetFlightsResponse, error)
}

type publicQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicQueryClient(cc grpc.ClientConnInterface) PublicQueryClient {
	return &publicQueryClient{cc}
}

func (c *publicQueryClient) IsServiceReady(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/org.covid19.api.PublicQuery/IsServiceReady", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicQueryClient) GetCases(ctx context.Context, in *GetCasesRequest, opts ...grpc.CallOption) (*GetCasesResponse, error) {
	out := new(GetCasesResponse)
	err := c.cc.Invoke(ctx, "/org.covid19.api.PublicQuery/GetCases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicQueryClient) GetFlights(ctx context.Context, in *GetFlightsRequest, opts ...grpc.CallOption) (*GetFlightsResponse, error) {
	out := new(GetFlightsResponse)
	err := c.cc.Invoke(ctx, "/org.covid19.api.PublicQuery/GetFlights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicQueryServer is the server API for PublicQuery service.
type PublicQueryServer interface {
	IsServiceReady(context.Context, *empty.Empty) (*wrappers.BoolValue, error)
	GetCases(context.Context, *GetCasesRequest) (*GetCasesResponse, error)
	GetFlights(context.Context, *GetFlightsRequest) (*GetFlightsResponse, error)
}

// UnimplementedPublicQueryServer can be embedded to have forward compatible implementations.
type UnimplementedPublicQueryServer struct {
}

func (*UnimplementedPublicQueryServer) IsServiceReady(ctx context.Context, req *empty.Empty) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsServiceReady not implemented")
}
func (*UnimplementedPublicQueryServer) GetCases(ctx context.Context, req *GetCasesRequest) (*GetCasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCases not implemented")
}
func (*UnimplementedPublicQueryServer) GetFlights(ctx context.Context, req *GetFlightsRequest) (*GetFlightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlights not implemented")
}

func RegisterPublicQueryServer(s *grpc.Server, srv PublicQueryServer) {
	s.RegisterService(&_PublicQuery_serviceDesc, srv)
}

func _PublicQuery_IsServiceReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicQueryServer).IsServiceReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.covid19.api.PublicQuery/IsServiceReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicQueryServer).IsServiceReady(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicQuery_GetCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicQueryServer).GetCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.covid19.api.PublicQuery/GetCases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicQueryServer).GetCases(ctx, req.(*GetCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicQuery_GetFlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicQueryServer).GetFlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.covid19.api.PublicQuery/GetFlights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicQueryServer).GetFlights(ctx, req.(*GetFlightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublicQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.covid19.api.PublicQuery",
	HandlerType: (*PublicQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsServiceReady",
			Handler:    _PublicQuery_IsServiceReady_Handler,
		},
		{
			MethodName: "GetCases",
			Handler:    _PublicQuery_GetCases_Handler,
		},
		{
			MethodName: "GetFlights",
			Handler:    _PublicQuery_GetFlights_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public.svc.proto",
}
